spring:
  cloud:
    stream:
      bindings:
        output-out-0:
          destination: userCreated
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092
