spring:
  cloud:
    stream:
      function:
        definition: handleEvents
      bindings:
        handleEvents-in-0:
          destination: myapp.moderationdb.outbox_events
          content-type: application/json

      kafka:
        binder:
          brokers: localhost:9092

user:
  service:
    url: http://localhost:8081

