spring:
  cloud:
    stream:
      bindings:
        handlePostEvents-in-0:
          destination: myapp.postdb.outbox_events
          group: post-event-consumer
          content-type: application/json
      kafka:
        binder:
          brokers: broker:29092


#post:
#  service:
#    url: http://localhost:8082


# for docker
post:
  service:
    url: http://post-service:8082