services:
  broker:
    image: confluentinc/cp-kafka:7.5.0
    container_name: broker
    hostname: broker
    ports:
      - 9092:9092
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT, EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092, EXTERNAL://localhost:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@broker:29093"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    networks:
      - my-network
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "broker:29092", "--list" ]
      interval: 10s
      timeout: 10s
      retries: 5

#  control-center:
#    image: confluentinc/cp-enterprise-control-center:7.5.0
#    container_name: control-center
#    depends_on:
#      broker:
#        condition: service_healthy
#    ports:
#      - 9021:9021
#    environment:
#      CONTROL_CENTER_BOOTSTRAP_SERVERS: broker:29092
#      CONTROL_CENTER_REPLICATION_FACTOR: 1
#      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
#      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
#      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
#      PORT: 9021
#    networks:
#      - my-network

networks:
  my-network:
    driver: bridge
